---
title: "MAG — S2 WRANGLING EDA"
author: "ANONYMIZED"
date: "2024-02-04"
output:
  html_document:
    theme: flatly
    code_folding: hide
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    toc_depth: 5
  pdf_document:
    toc: yes
    toc_depth: '4'
always_allow_html: yes
font-family: DejaVu Sans
mainfont: DejaVu Sans
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#UTILITIES
library(Hmisc) # %nin% operator
library(tidyverse) #all the things
library(magrittr) #special pipes like %<>%
library(summarytools) #data quality
library(jtools) #Social Science regression utilities
library(lubridate) #dealing with dates

#VIZ
library(kableExtra) #printing tables
library(ggformula) #regression syntax viz
# library(vcd) #mosaic plots
# library(vcdExtra) #mosaic plot helpers
library(ggstatsplot) #dummies
library(GGally) #extends ggplot for EDA 

#MODELLING
library(easystats) #modelling helpers
library(see)
library(sjPlot)
library(lme4)
library(lmerTest) #for CIs in glmer

options(readr.show_col_types = FALSE) #don't show coltypes on read_csv

#POWER ANALYSIS & SIMULATION
library(pwr)
library(simr)

#ARF ONLY — MANUAL RUN
# setwd("~/Code/IXN-Characterizing_Interaction/IXN-D_Characterizing_Interaction/ANALYSIS")

```

TODO describe provenance

```{r WRANGLING, message=FALSE, warning=FALSE}

#DF_RAW --> will always be the unaltered version of imported data
# 1 row per subject 
df_raw <- read_csv("data/CLEAN_MAG-VIS_S2_prototype_v5.csv", col_names = TRUE)




## TODO HANDLE CONSENT AND ELIGIBILITY 
## TODO HANDLE STUDY_ID AND SESSION_ID



#### MASTER WIDE FORMAT DATA FRAME ##########################
# 1 row per subject
  # drop first two rows (qualtrics_specs)
df_master <- df_raw[-c(1:2),] %>% select(
#### TODO REMOVE TEMPORARY DROP COLUMNS THAT ARE ONLY HERE FOR TESTING
  -contains("Q783"), -T_EMAIL, -(Q682_1:Q680_1), -contains("TEST")
  ) %>% select(
    -EndDate, -IPAddress,-Progress,-RecordedDate,
    -RecipientLastName, -RecipientFirstName, -RecordedDate, -RecipientEmail,
    -ExternalReference, -LocationLatitude, -LocationLongitude, 
    -BROWSER_Version, -BROWSER_Resolution,
    -UserLanguage, -Q_RecaptchaScore, 
    -CONSENT, -ELIGIBILITY, 
    -stimulus_common,
    -contains("First Click"), -contains("Last Click"), -contains("Click Count")
  )  %>% rename(
    duration.sec = `Duration (in seconds)`,
    PLATFORM = Q_PLATFORM,
    ORDER = FL_74_DO,
    ID.Qualtrics = ResponseId,
    ID.Prolific = PROLIFIC_PID,
    ID.Study = STUDY_ID,
    ID.Session = SESSION_ID,
    BROWSER_OS = `BROWSER_Operating System`
  ) %>% mutate(
    StartDate = mdy_hm(StartDate),
    duration.sec = as.numeric(duration.sec), #weird booleans should only be for the test generator
    duration.min = duration.sec/60
  ) %>% rename_at(
    #REPLACE RANDOM TRAILING _1 AND _65 FROM QUALTRICS
    vars(contains('_65')), funs(sub('_65', '', .))
    ) %>% rename_at(
    vars(contains('_1')), funs(sub('_1', '', .))
  ) %>% rename_at(
    vars(contains('_Page Submit')), funs(sub('_Page Submit', '', .))
  ) %>% rename_at( #CHANGE DETAIL QUESTION DELIMITER FOR PIVOT PURPOSES 
    vars(contains('_CHART_')), funs(sub('_CHART_', '_CHART-', .))
  ) %>% rename_at( #CHANGE DETAIL QUESTION DELIMITER FOR PIVOT PURPOSES 
    vars(contains('_MAKER_')), funs(sub('_MAKER_', '_MAKER-', .))
  ) %>% rename_at( #CHANGE DETAIL QUESTION DELIMITER FOR PIVOT PURPOSES 
    vars(contains('_TOOL_')), funs(sub('_TOOL_', '_TOOL-', .))
  ) 

##NEXT   
##TODO HANDLE LOOP NUMBERS 

#### MASTER SUBJECT DATA FRAME ##########################
# 1 row per subject 
# TODO HANDLE DEMOGRAPHICS WHEN THEY'RE ADDED 
df_subjects <- df_master %>% select(
  ID.Qualtrics, ID.Prolific, duration.sec, duration.min,
  PLATFORM, ORDER,Status,
  StartDate,  Finished, DistributionChannel,
  contains("BROWSER"), contains("D-"), contains("SCREEN")
)  
  


#### QUESTION LEVEL DATA FRAME (LONG) ##########################
# 1 row per participant X graph X question
#TODO NOTE THIS MISSES THE LOOP NUMBER
df_question <- df_master %>% select(
  ID.Qualtrics, PLATFORM, 
  contains("Q_"), contains("_Q")
) %>% pivot_longer( #PIVOT ON stimulus
  cols = contains("_Q"),
  names_to = c("stimulus","dummy","BLOCK","QUESTION"),
  values_to = c("value"),
  names_sep = "_"
) %>% select(-dummy) %>% unite(
   BLOCK:stimulus, col="STIMULUS", sep="-", remove=FALSE
) %>% mutate(
  BLOCK = BLOCK,
  STIMULUS = STIMULUS,
  QUESTION = QUESTION
) %>% select(-stimulus) %>% filter(!is.na(value))
  


#### CHART LEVEL DATA FRAME (LONG) ##########################
# 1 row per participant X graph 
df_chart <- df_question %>% 
  pivot_wider(
    names_from = QUESTION,
    values_from = value
  )



#CHECK BLOCKS PER PARTICIPANT
# every participant should have 2 blocks
check_subject_blocks <- df_question %>%
  group_by(ID.Qualtrics) %>% summarise(
    n_block = length(unique(BLOCK))
  )
  

#CHECK STIMULI PER PARTICIPANT
# every participant should have 5 graphs
check_subject_stimuli <- df_question %>% 
  group_by(ID.Qualtrics) %>%summarise(
    n_graphs = length(unique(STIMULUS))
  ) #each participant should have two blocks

```