---
title: "MAG — S2 WRANGLING EDA"
author: "ANONYMIZED"
date: "2024-02-04"
output:
  html_document:
    theme: flatly
    code_folding: hide
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    toc_depth: 5
  pdf_document:
    toc: yes
    toc_depth: '4'
always_allow_html: yes
font-family: DejaVu Sans
mainfont: DejaVu Sans
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#UTILITIES
library(Hmisc) # %nin% operator
library(tidyverse) #all the things
library(magrittr) #special pipes like %<>%
library(summarytools) #data quality
library(jtools) #Social Science regression utilities
library(lubridate) #dealing with dates

#VIZ
library(kableExtra) #printing tables
library(ggformula) #regression syntax viz
# library(vcd) #mosaic plots
# library(vcdExtra) #mosaic plot helpers
library(ggstatsplot) #dummies
library(GGally) #extends ggplot for EDA 

#MODELLING
library(easystats) #modelling helpers
library(see)
library(sjPlot)
library(lme4)
library(lmerTest) #for CIs in glmer

options(readr.show_col_types = FALSE) #don't show coltypes on read_csv

#POWER ANALYSIS & SIMULATION
library(pwr)
library(simr)

#ARF ONLY — MANUAL RUN
# setwd("~/Code/IXN-Characterizing_Interaction/IXN-D_Characterizing_Interaction/ANALYSIS")

```

TODO describe provenance

```{r WRANGLING, message=FALSE, warning=FALSE}

#DF_RAW --> will always be the unaltered version of imported data
# 1 row per subject 
df_raw <- read_csv("data/CLEAN_MAG-VIS_S2_prototype.csv", col_names = TRUE)

#### MASTER WIDE FORMAT DATA FRAME ##########################
# 1 row per subject
  # drop first two rows (qualtrics_specs)
df_master <- df_raw[-c(1:2),] %>% select(
    -EndDate, -IPAddress,-Progress,-RecordedDate,
    -RecipientLastName, -RecipientFirstName, -RecordedDate, -RecipientEmail,
    -ExternalReference, -LocationLatitude, -LocationLongitude, 
    -BROWSER_Version, -BROWSER_Resolution,
    -UserLanguage, -Q_RecaptchaScore, -Q_PLATFORM,
    -randomize_academic_DO,-randomize_news_DO,-randomize_infograph_DO,-randomize_indy_DO,
    -`Q_COMM_MAKER_LATENCY_First Click`, -`Q_COMM_MAKER_LATENCY_Last Click`, -`Q_COMM_MAKER_LATENCY_Click Count`,
    -`Q_COMM_CHART_LATENCY_First Click`,-`Q_COMM_CHART_LATENCY_Last Click`,-`Q_COMM_CHART_LATENCY_Click Count`,
    -`Q_ACAD_MAKER_LATENCY_First Click`,-`Q_ACAD_MAKER_LATENCY_Last Click`,-`Q_ACAD_MAKER_LATENCY_Click Count`,
    -`Q_ACAD_CHART_LATENCY_First Click`,-`Q_ACAD_CHART_LATENCY_Last Click`,-`Q_ACAD_CHART_LATENCY_Click Count`,
    -`Q_NEWS_MAKER_LATENCY_First Click`,-`Q_NEWS_MAKER_LATENCY_Last Click`,-`Q_NEWS_MAKER_LATENCY_Click Count`,
    -`Q_NEWS_CHART_LATENCY_First Click`,-`Q_NEWS_CHART_LATENCY_Last Click`,-`Q_NEWS_CHART_LATENCY_Click Count`,
    -`Q_INFO_MAKER_LATENCY_First Click`,-`Q_INFO_MAKER_LATENCY_Last Click`,-`Q_INFO_MAKER_LATENCY_Click Count`,
    -`Q_INFO_CHART_LATENCY_First Click`,-`Q_INFO_CHART_LATENCY_Last Click`,-`Q_INFO_CHART_LATENCY_Click Count`,
    -`Q_IND_MAKER_LATENCY_First Click`,-`Q_IND_MAKER_LATENCY_Last Click`,-`Q_IND_MAKER_LATENCY_Click Count`,
    -`Q_IND_CHART_LATENCY_First Click`,-`Q_IND_CHART_LATENCY_Last Click`,-`Q_IND_CHART_LATENCY_Click Count`,
    -stimulus_common, -stimulus_academic, -stimulus_news, -stimulus_infographic, -stimulus_indy,
    -randomize_common, -randomize_common_DO,
    -CONSENT, -ELIGIBILITY, stimulus_common
  ) %>% select(
    #TEMP ONLY BEFORE DEMOGRAPHICS Q NAMES ARE FINALIZED
    !contains("Q1")
  ) %>% rename(
    ID.QUALTRICS = ResponseId,
    ID.PROLIFIC = ID_PROLIFIC,
    duration.sec = `Duration (in seconds)`,
    BROWSER_OS = `BROWSER_Operating System`,
    graph_common = stimulus_common,
    graph_academic =     randomize_academic,
    graph_news =         randomize_news,
    graph_infographic =  randomize_infograph,
    graph_independent =  randomize_indy,
    ORDER = FL_74_DO,
    Q_COMM_MAKER_LATENCY = `Q_COMM_MAKER_LATENCY_Page Submit`, 
    Q_COMM_CHART_LATENCY = `Q_COMM_CHART_LATENCY_Page Submit`, 
    Q_ACAD_MAKER_LATENCY = `Q_ACAD_MAKER_LATENCY_Page Submit`, 
    Q_ACAD_CHART_LATENCY = `Q_ACAD_CHART_LATENCY_Page Submit`, 
    Q_NEWS_MAKER_LATENCY = `Q_NEWS_MAKER_LATENCY_Page Submit`, 
    Q_NEWS_CHART_LATENCY = `Q_NEWS_CHART_LATENCY_Page Submit`, 
    Q_INFO_MAKER_LATENCY = `Q_INFO_MAKER_LATENCY_Page Submit`, 
    Q_INFO_CHART_LATENCY = `Q_INFO_CHART_LATENCY_Page Submit`, 
    Q_IND_MAKER_LATENCY = `Q_IND_MAKER_LATENCY_Page Submit` , 
    Q_IND_CHART_LATENCY = `Q_IND_CHART_LATENCY_Page Submit` 
  ) %>% mutate(
    StartDate = mdy_hm(StartDate),
    duration.sec = as.numeric(duration.sec), #weird boolean data should only be for the test generator
    duration.min = duration.sec/60
  ) 

## LEFT OFF HERE ,,, START UP BY GETTING COMMON GRAPH URL FROM GRAPH COMMON

#string replace trailing _1 and _65 on some columns (weird qualtrics)  
colnames(df_master) = gsub("_1", "", colnames(df_master))
colnames(df_master) = gsub("_65", "", colnames(df_master))
colnames(df_master) = gsub("...56", "", colnames(df_master))
colnames(df_master) = gsub("...58", "", colnames(df_master))

#HARDCODE COMMON GRAPH ID 
df_data$graph_common = ""

#### MASTER SUBJECT DATA FRAME ##########################
# 1 row per subject 
# TODO HANDLE DEMOGRAPHICS WHEN THEY'RE ADDED 
df_subjects <- df_master %>% select(
  ID.QUALTRICS, ID.PROLIFIC, duration.sec, duration.min,
  StartDate, Status, Finished, DistributionChannel,
  contains("BROWSER") ,PLATFORM, ORDER, contains("graph_")
)

#### MASTER RESPONSE DATA FRAME (WIDE) ##########################
# 1 row per subject 
# only subject and important graph data 
df_data <- df_master %>% select(
  ID.QUALTRICS, PLATFORM, duration.min, 
  contains("Q_"), contains("graph_")
)

test <- df_data %>% 
  select(
    ID.QUALTRICS, contains("Q_"), contains("graph_")
    ) %>% 
  pivot_longer( #PIVOT ON GRAPH
    cols = contains("graph"),
    names_to = c("dummy","genre"),
    values_to = c("graph"),
    names_sep = "_"
  ) %>% select(-dummy) %>% 
  pivot_longer( #PIVOT ON QUESTIONS
    cols = contains("Q_"), 
    names_to = c("DUMMY","TRIAL", "SECTION", "QUESTION"),
    names_sep = "_",
    values_to = "response"
    ) %>% select(-DUMMY) %>% 
  unite(
    col= "QUESTION",
    SECTION:QUESTION,
    sep= "_", 
    remove = TRUE
  ) 

temp_common <- test %>% filter(
  TRIAL == "COMM"
)

# %>%  mutate( genre = case_when(
    TRIAL == "COMM" ~ "common"  
  ))
    
  
  
  #(GENRE == "COMM"), 
    genre = comm, graph = "test"
  )





```