---
title: "MAG — S0  SUMMER PILOT EDA"
author: "ANONYMIZED"
date: "2024-01-27"
output:
  html_document:
    theme: flatly
    code_folding: hide
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    toc_depth: 5
  pdf_document:
    toc: yes
    toc_depth: '4'
always_allow_html: yes
font-family: DejaVu Sans
mainfont: DejaVu Sans
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#UTILITIES
library(Hmisc) # %nin% operator
library(tidyverse) #all the things
library(summarytools) #data quality
library(jtools) #Social Science regression utilities
library(lubridate) #dealing with dates

#VIZ
library(kableExtra) #printing tables
library(ggformula) #regression syntax viz
# library(vcd) #mosaic plots
# library(vcdExtra) #mosaic plot helpers
library(ggstatsplot) #dummies

#MODELLING
library(easystats) #modelling helpers
library(see)
library(sjPlot)
library(lme4)
library(lmerTest) #for CIs in glmer

options(readr.show_col_types = FALSE) #don't show coltypes on read_csv


#ARF ONLY — MANUAL RUN
# setwd("~/Code/IXN-Characterizing_Interaction/IXN-D_Characterizing_Interaction/ANALYSIS")

```

Data were exported from qualtrics to file `RAW_Vis Guise Pre-Pilot_January 27, 2024_16.57.csv` which was manually wrangled to `CLEAN_pilot_0.csv` by removing extraneous qualtrics columns and creating informative column names from question text. 


```{r IMPORT, message=FALSE, warning=FALSE}

#DF RAW 1 ROW PER PARTICIPANT
df_raw <- read_csv("data/CLEAN_S0_pilot.csv")

#DF DATA 1 ROW PER PARTICIPANT
#PRELIM-CLEANING
df_data <- df_raw %>% filter(
  finished_survey == 'TRUE'#EXCLUDE non-finishers
) %>% filter(
  !(is.na(IPAddress)) #EXCLUDE no ip address [from survey preview]
) %>% select( #drop unecessary columns
  -StartDate, -EndDate, -IPAddress, -Progress, -finished_survey, -RecordedDate,
  -latitude, -longitude, -source, -language, -consent, -eligibility, -responseID,
  -Status
) %>% rename( #rename for consistency
  ID.PROLIFIC = prolificID,
  duration.sec = duration_sec 
) %>% mutate( #factorize 
  duration.min = round(duration.sec/60,1)
) %>% relocate(
  duration.min, .after=duration.sec
) %>% relocate(ID.PROLIFIC) 
# %>% JK DON'T FACTORIZE THIS IS GOING TO BE A PROBLEM POST PIVOT
#   mutate ( #factorize if NOT free response but IS a character
#   across(c(where(is.character),-contains("_explain"),-contains("_why")), factor)
# )  

#DF FREE 1 ROW PER PARTICIPANT
#GET ALL THE FREE RESPONSE DATA
df_free <- df_data %>% select(
  ID.PROLIFIC, duration.sec, duration.min,
  contains("_explain"), contains("_why"), contains("_who")
) 

#DF DEMOS 1 ROW PER PARTICIPANT
#WS SURVEY and DEMOGRAPHICS
df_demographics <- df_data %>% select(
  ID.PROLIFIC, duration.sec, duration.min, contains("ws_"), contains("p_")
)

#DF DATA 1 ROW PER PARTICIPANT
#DROP DEMOS and COMPREHENSION and FREE
df_data <- df_data %>% 
  select(
    -contains("ws_"), -contains("p_"), 
    -contains("_explain"), -contains("_why"), -contains("_who"),
    -contains("q1"), -contains("q2"), -contains("q3")
  )

# #DF CHART 1 ROW PER PARTICIPANT-CHART-QUESTION
# #RESHAPE 
df_graphs <- df_data  %>% 
  pivot_longer( #PIVOT ALL THE WAY LONG
    cols = v1_chart_intent:v5_author_confidence,
    names_to = c("graph","subject","question"),
    # names_pattern = "(v.)(chart.)(.)"
    names_sep = "_") %>% 
  unite( #COMBINE SUBJECT AND QUESTION
    col = "question", 
    subject:question, 
    sep="_",
    remove = TRUE) %>% 
  pivot_wider( #NOW PIVOT BACK UP ONE LEVEL
    names_from = question,
    values_from=value
  ) %>% mutate_if(#RE-FACTORIZE
    is.character,factor
  ) %>% mutate( #SET LEVELS
    chart_intent = factor (chart_intent,
      levels = c("Seeking to inform","2","3","4","Seeking to persuade","Don't know/Can't Say"),
      labels = c("inform","2","3","4","persuade","?")),
    chart_politics = factor(chart_politics,
      levels = c("Politically motivated","2","3","4","Not politically motivated","Don't know/Can't Say"),
      labels = c("political","2","3","4","not-political","?")),
    chart_bias = factor(chart_bias,
      levels = c("Biased","2","3","4","Unbiased","Don't know/Can't Say"),
      labels = c("baised","2","3","4","unbiased","?")),
    chart_complexity = factor(chart_complexity, 
      levels = c("Manipulative","2","3","4","Straightforward","Don't know/Can't Say"),
      labels = c("manipulative",  "2",  "3",  "4",  "straightforward",  "?")),
    chart_confidence = factor(chart_confidence,
      levels = c("Extremely unconfident", "Somewhat unconfident", "Neither confident nor unconfident",  
                 "Somewhat confident","Extremely confident"),
      labels = c("1","2","3","4","5")),
    author_expertise = factor(author_expertise,
      levels = c("Amateur", "2","3", "Expert","Don't know/Can't say"),
      labels = c("amateur","2","3","expert","?")),
    author_responsibility = factor(author_responsibility,
      levels = c("Responsible", "2", "3", "Irresponsible","Don't know/Can't say"),
      labels = c("responsible","2", "3","irresponsible","?")),
    author_honesty = factor(author_honesty,
      levels = c("Honest", "2", "3", "Dishonest","Don't know/Can't say"),
      labels = c("honest","2", "3","dishonest","?")),
    author_grounded = factor(author_grounded,
      levels = c("Down to earth", "2", "3", "Out of touch","Don't know/Can't say"),
      labels = c("grounded","2", "3","not-grounded","?")),
    author_alignment = factor(author_alignment,
      levels = c("Like you", "2", "3", "Unlike you","Don't know/Can't say"),
      labels = c("like-me","2", "3","unlike-me","?")),
    author_confidence = factor(author_confidence,
      levels = c("Extremely unconfident", "Somewhat unconfident", "Neither confident nor unconfident",  
                 "Somewhat confident","Extremely confident"),
      labels = c("1","2","3","4","5"))
  )    
    
```



```{r vis}

#PAIRPLOT



```








```{r CHART-SD}
#JUST THE CHART RELATED SD QUESTIONS
df_chart <- df_data %>% 
  select(responseID,duration_sec,
    contains("chart")
  ) 

#THIS IS THE SUPER COMPACT CODE
#BUT ITS NOT HELPFUL BC WE CAN'T FACTORIZE THE SCALE COL
#WITH ALL THE DIFF BIPLOAR VALUES
df_compact_chart <- df_chart %>%
  select(responseID, duration_sec, contains("chart")) %>%
  select(!contains(c("why","explain"))) %>%
  pivot_longer(
    cols=(contains("chart")),
    names_to = "vis",
    values_to = "scale"
  ) %>% mutate(
    question = str_sub(vis,10),
    vis = str_sub(vis,1,2),
    vis = factor(vis,
        levels = c("v1","v3","v2","v4","v5"),
        labels = c("econ-parks","econ-iraq","mil-spend","bears","trees"))
  )

gf_bar(data = df_compact_chart, ~scale) %>% 
  gf_facet_grid(.~question) + theme_minimal()



##CHART INTENT
df_intent <- df_compact_chart %>% 
  filter(question =="intent") %>% 
  mutate(
    scale = factor(scale,
                   levels = c(
                     "Seeking to inform",
                     "2",
                     "3",
                     "4",
                     "Seeking to persuade",
                     "Don't know/Can't Say"
                   ),
                    labels = c(
                     "inform",
                     "2",
                     "3",
                     "4",
                     "persuade",
                     "?"
                   ))
  )


gf_bar(data = df_intent, ~scale) %>% 
  gf_facet_grid(vis~.) + theme_minimal()


##CHART POLITICS
df_politics <- df_compact_chart %>% 
  filter(question =="politics") %>% 
  mutate(
    scale = factor(scale,
                   levels = c(
                     "Politically motivated",
                     "2",
                     "3",
                     "4",
                     "Not politically motivated",
                     "Don't know/Can't Say"
                   ),
                   labels = c(
                     "political",
                     "2",
                     "3",
                     "4",
                     "apolitical",
                     "?"
                   ))
  )

gf_bar(data = df_politics, ~scale) %>% 
  gf_facet_grid(vis~.) + theme_minimal()


##CHART BIAS
df_bias <- df_compact_chart %>% 
  filter(question =="bias")  %>% 
  mutate(
    scale = factor(scale,
                   levels = c(
                     "Biased",
                     "2",
                     "3",
                     "4",
                     "Unbiased",
                     "Don't know/Can't Say"
                   ),
                   labels = c(
                     "baised",
                     "2",
                     "3",
                     "4",
                     "unbiased",
                     "?"
                   ))
  )

gf_bar(data = df_bias, ~scale) %>% 
  gf_facet_grid(vis~.) + theme_minimal()


##CHART COMPLEXITY
df_complexity <- df_compact_chart %>% 
  filter(question =="complexity") %>% 
  mutate(
    scale = factor(scale,
                   levels = c(
                     "Manipulative",
                     "2",
                     "3",
                     "4",
                     "Straightforward",
                     "Don't know/Can't Say"
                   ),
                   labels = c(
                     "manipulative",
                     "2",
                     "3",
                     "4",
                     "straightforward",
                     "?"
                   ))
  )

gf_bar(data = df_complexity, ~scale) %>% 
  gf_facet_grid(vis~.) + theme_minimal()

##CHART CONFIDENCE
df_chart_confidence <- df_compact_chart %>% 
  filter(question =="confidence") %>% 
  mutate(
    scale = factor(scale,
                   levels = c(
                     "Extremely unconfident",
                     "Somewhat unconfident",
                     "Neither confident nor unconfident",
                     "Somewhat confident",
                     "Extremely confident"
                   ))
  )

gf_bar(data = df_chart_confidence, ~scale) %>% 
  gf_facet_grid(vis~.) + theme_minimal()
```

